import { LinkedList } from "../../utils/linked-list"
import RoutePin from "./route-pin"

/**
 * 🗺 The Route generated by a group of `RoutePin`,
 * in practices, this class is a linked list of RoutePin.
 *
 * Created by chcmatos <carlos.matos@capgemini.com>, february 22 of 2022.
 *
 * @author Carlos Matos
 * @see RoutePin
 * @see LinkedList
 */
export default class Route extends LinkedList<RoutePin> {}
